# Exploitation de données électorales avec Python

## Import des données

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv(
 'https://www.data.gouv.fr/fr/datasets/r/182268fc-2103-4bcb-a850-6cf90b02a9eb'
)
print(f"Shape : {df.shape}")
df.head()

Shape : (528675, 7)

/tmp/ipykernel_24077/3312880608.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

,code_departement,libelle_departement,code_commune,libelle_commune,prenom,nom,voix
0,01,Ain,1,L'Abergement-Clémenciat,Nathalie,ARTHAUD,3
1,01,Ain,2,L'Abergement-de-Varey,Nathalie,ARTHAUD,2
2,01,Ain,4,Ambérieu-en-Bugey,Nathalie,ARTHAUD,38
3,01,Ain,5,Ambérieux-en-Dombes,Nathalie,ARTHAUD,8
4,01,Ain,6,Ambléon,Nathalie,ARTHAUD,0

## 1. Explorations générales

### Question 1

#### variable `code_commune`

In [3]:
from rep.explorations_generales import taille_max_code_commune, nb_occurence_longueur_code_departement, departement_11_caractères, maj_code_commune, verification_Montrouge

/home/onyxia/work/evaluation_intermediaire_python_ds/rep/explorations_generales.py:104: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

In [4]:
taille_max_code_commune(df)

La taille maximale du code commune est de 3 caractères.

In [5]:
nb_occurence_longueur_code_departement(df)
print("")
departement_11_caractères(df)

code_departement
2     522300
3       3225
11      3150
Name: count, dtype: int64

Valeurs suspectes dans code_departement :
['fr_etranger']

Extrait des lignes correspondantes :
      code_departement              libelle_departement  code_commune  \
35035      fr_etranger  Français établis hors de France             1
35036      fr_etranger  Français établis hors de France             2
35037      fr_etranger  Français établis hors de France             3
35038      fr_etranger  Français établis hors de France             4
35039      fr_etranger  Français établis hors de France             6

      libelle_commune    prenom      nom  voix
35035         Abidjan  Nathalie  ARTHAUD     7
35036       Abou Dabi  Nathalie  ARTHAUD     4
35037           Abuja  Nathalie  ARTHAUD     0
35038           Accra  Nathalie  ARTHAUD     0
35039     Addis Abeba  Nathalie  ARTHAUD     1

Pour créer un `code_commune` unique, nous mettons d’abord le code commune sur 3 chiffres (en ajoutant des zéros à gauche), puis nous le concaténons au code département.

Cette méthode couvre les 4 cas du dataset :
- Classique : Code à 5 chiffres, `92` + `049` → `92049`
- Outre-mer : Code à 6 chiffres, `971` + `001` → `971001`
- Corse (avec lettre) : Code contenant une lettre, `2A` + `001` → `2A001`
- Étranger : Texte suivi de 3 chiffres, `fr_etranger` + `001` → `fr_etranger001`

In [6]:
maj_code_commune(df)
verification_Montrouge(df)

Exemple Montrouge :
      code_commune libelle_commune
34535        92049       Montrouge

#### variable `candidat`

In [7]:
from rep.explorations_generales import entites_uniques, creation_candidat, aperçu_des_candidats

In [8]:
entites_uniques(df)

              nom    prenom
0         ARTHAUD  Nathalie
1   DUPONT-AIGNAN   Nicolas
2         HIDALGO      Anne
3           JADOT   Yannick
4        LASSALLE      Jean
5          LE PEN    Marine
6          MACRON  Emmanuel
7       MÉLENCHON  Jean-Luc
8          POUTOU  Philippe
9        PÉCRESSE   Valérie
10        ROUSSEL    Fabien
11        ZEMMOUR      Éric
12    abstentions       NaN
13         blancs       NaN
14           nuls       NaN

In [9]:
creation_candidat(df)
aperçu_des_candidats(df)

Aperçu des candidats :
['Nathalie ARTHAUD' 'Fabien ROUSSEL' 'Emmanuel MACRON' 'Jean LASSALLE'
 'Marine LE PEN']

In [10]:
df.head()

,code_departement,libelle_departement,code_commune,libelle_commune,prenom,nom,voix,candidat
0,01,Ain,01001,L'Abergement-Clémenciat,Nathalie,ARTHAUD,3,Nathalie ARTHAUD
1,01,Ain,01002,L'Abergement-de-Varey,Nathalie,ARTHAUD,2,Nathalie ARTHAUD
2,01,Ain,01004,Ambérieu-en-Bugey,Nathalie,ARTHAUD,38,Nathalie ARTHAUD
3,01,Ain,01005,Ambérieux-en-Dombes,Nathalie,ARTHAUD,8,Nathalie ARTHAUD
4,01,Ain,01006,Ambléon,Nathalie,ARTHAUD,0,Nathalie ARTHAUD

### Question 2

In [11]:
from rep.explorations_generales import nb_candidats

In [12]:
nb_candidats(df)

En 2022, il y avait 12 candidats à l'élection présidentielle.

Liste des candidats :
  - Anne HIDALGO
  - Emmanuel MACRON
  - Fabien ROUSSEL
  - Jean LASSALLE
  - Jean-Luc MÉLENCHON
  - Marine LE PEN
  - Nathalie ARTHAUD
  - Nicolas DUPONT-AIGNAN
  - Philippe POUTOU
  - Valérie PÉCRESSE
  - Yannick JADOT
  - Éric ZEMMOUR

### Question 3

In [13]:
from rep.explorations_generales import q3

In [14]:
q3(df)

Résultats du premier tour (10 avril 2022)
                 Candidat Nombre votes (total) Score (% votes exprimés)
0         Emmanuel MACRON            9 783 058                   27.85%
1           Marine LE PEN            8 133 828                   23.15%
2      Jean-Luc MÉLENCHON            7 712 520                   21.95%
3            Éric ZEMMOUR            2 485 226                    7.07%
4        Valérie PÉCRESSE            1 679 001                    4.78%
5           Yannick JADOT            1 627 853                    4.63%
6           Jean LASSALLE            1 101 387                    3.13%
7          Fabien ROUSSEL              802 422                    2.28%
8   Nicolas DUPONT-AIGNAN              725 176                    2.06%
9            Anne HIDALGO              616 478                    1.75%
10        Philippe POUTOU              268 904                    0.77%
11       Nathalie ARTHAUD              197 094                    0.56%

## 2. Comparaison des scores départements aux moyennes nationales

### Question 4

### Question 5

### Question 6

### Question 7

## 3. Un peu de cartographie